### ISSUE TITLE
_.templateSettings breaking grunt build

### ISSUE THREAD

**Issue by chrisbuttery** [nib-components/underscore#1]
@anthonyshort 

https://github.com/nib-components/underscore/blob/master/index.js#L1063

So it seems that this object of regex's (..regii... regexeses...) is breaking the FE build in the feature/fonts branch.

```
components/boot
>> A special character was detected in this template. Inside template tags, the
>> \n and \r special characters must be escaped as \\n and \\r. (grunt 0.4.0+)
Warning: An error occurred while processing a template (Unexpected token    
ILLEGAL). Use --force to continue.
```

Any thoughts on this.

**Comment by anthonyshort** [comment]
I remember seeing this... It's grunt trying to parse some code in underscore as a template. The fix was added to grunt-component-build, in the template, it should use {{{ }}} instead of just two {{ }}

**Comment by chrisbuttery** [comment]
the package.json referenced `"grunt-component-build": "~0.4.2",` which isn't a valid release, correct ?

I changed it back to 0.4.1...then it broke in my face. Is 0.4.2 yet to be committed ?
